apiVersion: v1
kind: Service
metadata:
  name: kuboolin
  labels:
    app: kuboolin
spec:
  selector:
    app: kuboolin
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer